---
apiVersion: v1
kind: Template
metadata:
  name: migration-assessment
objects:
  - apiVersion: cloud.redhat.com/v1alpha1
    kind: Frontend
    metadata:
      name: migration-assessment
    spec:
      API:
        versions:
          - v1
      envName: ${ENV_NAME}
      title: Assisted Migration
      deploymentRepo: https://gitlab.cee.redhat.com/assisted-migration/migration-assessment-app
      frontend:
        paths:
          - /apps/migration-assessment
      image: ${IMAGE}:${IMAGE_TAG}
      module:
        manifestLocation: '/apps/migration-assessment/fed-mods.json'
        modules:
          - id: 'migration-assessment-app'
            module: './RootApp'
            routes:
              - pathname: /openshift/migration-assessment

parameters:
  - name: ENV_NAME
    required: true
  - name: IMAGE_TAG
    required: true
  - name: IMAGE
    value: quay.io/app-sre/migration-assessment
